name: Deploy on VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Connect to VPS and deploy
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22

          script: |
            cd /home/sp/projects/wheelsonfire || exit 1            
            docker build -t wheelsonfire .
            docker stop wheelsonfire.com || true
            docker rm wheelsonfire.com || true
            docker run -d --name wheelsonfire.com -p 8002:8002 wheelsonfire